http_server:
  port: "8080"

db_server:
  host: ""
  port: ""
  user: ""
  pass: ""
  name: ""
  max_conns: 10

http_client:
  timeout_seconds: 10

logging:
  level: "info"

exchange_rate_api:
  base_url: "https://v6.exchangerate-api.com/v6"
  api_key: ""

scheduler:
  update_rates_job_duration_sec: 30

cache:
  rate_updates_max_items: 512
